import React from "react";
import { Container, Row, Col } from "react-bootstrap";
import ProjectCard from "./ProjectCards";
import Particle from "../Particle";
import insectCatch from "../../Assets/Projects/Insect.png";
import githubProfile from "../../Assets/Projects/githubProfile.png";
import password from "../../Assets/Projects/passwordGenerator.png";

function Projects() {
  return (
    <Container fluid className="project-section">
      <Particle />
      <Container>
        <h1 className="project-heading">
          My Recent <strong className="purple">Works </strong>
        </h1>
        <p style={{ color: "white" }}>
          Here are a few projects I've worked on recently.
        </p>
        <Row style={{ justifyContent: "center", paddingBottom: "10px" }}>
          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={insectCatch}
              isBlog={false}
              title="Insect Catch Game"
              description="A fun and never ending game to spend your leisure time build with HTML, CSS and JavaScript. Have features to select your kind of insect and the image appears randomly at any location on your screen, you need to catch the insect."
              ghLink="https://github.com/kumarvishal3257/Insect-catch-game"
              demoLink="https://kumarvishal3257.github.io/Insect-catch-game/"
            />
          </Col>

          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={githubProfile}
              isBlog={false}
              title="Github Profile Viewer"
              description="A search box where user can search for any github username and get the data of the user including its repository, recent projects, image, etc. Build with HTML, CSS and JavaSCript to fetch data of the user using axios."
              ghLink="https://github.com/kumarvishal3257/Github-profile-viewer"
              demoLink="https://kumarvishal3257.github.io/Github-profile-viewer/"
            />
          </Col>

          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={password}
              isBlog={false}
              title="Password Generator"
              description="A random password generator app which helps user to generate passwords of their desired combination and length. Build using HTML, CSS and JavaScript. It also tells the strength of the password generated by the user."
              ghLink="https://github.com/kumarvishal3257/PasswordGenerator"
              demoLink="https://kumarvishal3257.github.io/PasswordGenerator/"              
            />
          </Col>

        </Row>
      </Container>
    </Container>
  );
}

export default Projects;
